/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC;

/**
 *
 * @author ProfVespertino
 */
public class VistaCalculadora extends javax.swing.JFrame implements InterfazCalculadora {

    private ControladorCalculadora controlador;

    /**
     * Creates new form VSCalculadora
     */
    public VistaCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(300, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldOp1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOp2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOperacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("Operando 1:");
        getContentPane().add(jLabel1);
        getContentPane().add(jTextFieldOp1);

        jLabel2.setText("Operando 2:");
        getContentPane().add(jLabel2);
        getContentPane().add(jTextFieldOp2);

        jLabel3.setText("Operación");
        getContentPane().add(jLabel3);

        jComboBoxOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        jComboBoxOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperacionActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOperacion);

        jLabel4.setText("Resultado");
        getContentPane().add(jLabel4);

        jLabelResultado.setText("xxx");
        getContentPane().add(jLabelResultado);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar);

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcular);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // Vacia los campos del JForm.
        jTextFieldOp1.setText("");
        jTextFieldOp2.setText("");
        jLabelResultado.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // Llama al controlador para que haga las operaciones.
        controlador.operar();
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jComboBoxOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOperacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldOp1;
    private javax.swing.JTextField jTextFieldOp2;
    // End of variables declaration//GEN-END:variables

    @Override
    public double getOperando1() {
        return Double.parseDouble(jTextFieldOp1.getText());
    }

    @Override
    public double getOperando2() {
        return Double.parseDouble(jTextFieldOp2.getText());
    }

    @Override
    public char getOperador() {
        String aux = (String) jComboBoxOperacion.getSelectedItem();
        return aux.charAt(0);
    }

    @Override
    public void setResultado(double resultado) {
        jLabelResultado.setText(resultado + "");
    }

    @Override
    public void setControlador(Object o) {
        controlador = (ControladorCalculadora) o;
    }

    @Override
    public void muestrate() {
        setVisible(true);
    }
}
